//! Pending OS-open requests outlive webview startup and event delivery.
use std::collections::VecDeque;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

#[derive(Default)]
pub struct OpenFileState(Mutex<VecDeque<String>>);

impl OpenFileState {
    pub fn enqueue(&self, paths: impl IntoIterator<Item = String>) {
        let mut pending = self.0.lock().unwrap_or_else(|error| error.into_inner());
        for path in paths {
            // Finder can deliver the same cold-start file through argv and
            // Opened. Deduplicate only pending requests, never future opens.
            if !pending.contains(&path) {
                pending.push_back(path);
            }
        }
    }

    pub fn has_pending(&self) -> bool {
        !self
            .0
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .is_empty()
    }

    pub fn pop(&self) -> Option<String> {
        self.0
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .pop_front()
    }

    pub fn drain(&self) -> Vec<String> {
        self.0
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .drain(..)
            .collect()
    }
}

/// Canonical editor labels generated by the native host. A label alone does not
/// establish that the host actually created or registered a live window.
pub(crate) fn document_window_number(label: &str) -> Option<u32> {
    if label == "main" {
        return Some(0);
    }
    let suffix = label.strip_prefix("window-")?;
    let number = suffix.parse::<u32>().ok()?;
    (number > 0 && suffix == number.to_string()).then_some(number)
}

/// Only backend-created document labels may consume native file requests.
/// The live Tauri window registry supplies these labels, never caller input.
/// Numeric order remains stable regardless of HashMap iteration order.
pub fn document_window_owner<'a>(labels: impl IntoIterator<Item = &'a str>) -> Option<&'a str> {
    labels
        .into_iter()
        .filter_map(|label| document_window_number(label).map(|number| (number, label)))
        .min_by_key(|(number, _)| *number)
        .map(|(_, label)| label)
}

pub fn is_supported_markdown_path(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| {
            extension.eq_ignore_ascii_case("md") || extension.eq_ignore_ascii_case("markdown")
        })
        .unwrap_or(false)
}

/// argv contains the executable first. OS file associations pass native paths;
/// URI/deep-link parsing belongs to its own ingress and must not decode paths.
pub fn paths_from_args(args: impl IntoIterator<Item = String>, cwd: Option<&Path>) -> Vec<String> {
    let mut literal_paths = false;
    args.into_iter()
        .skip(1)
        .filter_map(|argument| {
            if !literal_paths && argument == "--" {
                literal_paths = true;
                return None;
            }
            if argument.is_empty()
                || (!literal_paths && argument.starts_with('-'))
                || argument.contains("://")
            {
                return None;
            }
            let path = PathBuf::from(argument);
            if !is_supported_markdown_path(&path) {
                return None;
            }
            let absolute = if path.is_absolute() {
                path
            } else {
                cwd?.join(path)
            };
            if !absolute.is_absolute() {
                return None;
            }
            // Tauri's JS path contract is UTF-8. Do not replace invalid bytes with
            // U+FFFD and accidentally address a different file.
            absolute.into_os_string().into_string().ok()
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(values: &[&str], cwd: Option<&Path>) -> Vec<String> {
        paths_from_args(values.iter().map(|value| value.to_string()), cwd)
    }

    #[test]
    fn live_main_is_the_only_owner_even_if_other_documents_exist() {
        assert_eq!(
            document_window_owner(["window-1", "main", "window-2"]),
            Some("main")
        );
        assert_eq!(
            document_window_owner(["window-2", "main", "window-1"]),
            Some("main")
        );
    }

    #[test]
    fn remaining_documents_elect_one_stable_numeric_owner() {
        assert_eq!(
            document_window_owner(["window-10", "window-2", "window-3"]),
            Some("window-2")
        );
        assert_eq!(
            document_window_owner(["window-3", "window-2", "window-10"]),
            Some("window-2")
        );
    }

    #[test]
    fn print_preview_and_unregistered_labels_cannot_take_the_queue() {
        assert_eq!(
            document_window_owner([
                "window-print",
                "preview",
                "window-preview",
                "window-01",
                "window-0",
                "window-+1",
                "window-4294967296"
            ]),
            None
        );
        assert_eq!(document_window_owner(std::iter::empty()), None);
    }

    #[test]
    fn queued_requests_survive_owner_close_and_consumer_registration() {
        let pending = OpenFileState::default();
        pending.enqueue(["waiting.md".into()]);
        assert!(pending.has_pending());
        // Notification to main was missed as it closed. The next live owner
        // receives a new wakeup and drains the same pending request.
        let live = ["window-print", "main", "window-2", "window-1"];
        let owner = document_window_owner(live.into_iter().filter(|label| *label != "main"));
        assert_eq!(owner, Some("window-1"));
        assert_eq!(pending.drain(), vec!["waiting.md"]);
        assert!(!pending.has_pending());
        pending.enqueue(["later.md".into()]);
        assert_eq!(document_window_owner(["window-print"]), None);
        assert!(pending.has_pending());
        assert_eq!(
            document_window_owner(["window-print", "window-3"]),
            Some("window-3")
        );
        assert_eq!(pending.pop().as_deref(), Some("later.md"));
    }

    #[test]
    fn multiple_cli_paths_keep_order_and_literal_unicode_spaces_and_percent() {
        let cwd = std::env::temp_dir();
        let result = args(
            &["app", "日本語 文書.md", "second.MARKDOWN", "100%25.md"],
            Some(&cwd),
        );
        assert_eq!(
            result,
            ["日本語 文書.md", "second.MARKDOWN", "100%25.md"].map(|path| cwd
                .join(path)
                .into_os_string()
                .into_string()
                .unwrap())
        );
    }

    #[test]
    fn cli_uses_sender_cwd_and_keeps_absolute_path() {
        let cwd = std::env::temp_dir().join("sender");
        let absolute = std::env::temp_dir().join("absolute.md");
        let result = args(
            &["app", "relative.md", absolute.to_str().unwrap()],
            Some(&cwd),
        );
        assert_eq!(
            result,
            vec![
                cwd.join("relative.md").to_str().unwrap(),
                absolute.to_str().unwrap()
            ]
        );
    }

    #[test]
    fn flags_uris_unsupported_and_empty_args_are_not_documents() {
        assert!(args(
            &[
                "app",
                "--inspect.md",
                "file:///tmp/a.md",
                "https://example/a.md",
                "md-workbench://open/a.md",
                "a.txt",
                ""
            ],
            Some(Path::new("/"))
        )
        .is_empty());
        assert!(args(&["app"], Some(Path::new("/"))).is_empty());
        assert!(args(&["app", "relative.md"], None).is_empty());
        assert!(args(&["app", "relative.md"], Some(Path::new("relative-cwd"))).is_empty());
    }

    #[test]
    fn double_dash_allows_filename_starting_with_dash() {
        let cwd = std::env::temp_dir();
        assert_eq!(
            args(&["app", "--", "-notes.md"], Some(&cwd)),
            vec![cwd.join("-notes.md").to_str().unwrap()]
        );
    }

    #[test]
    fn long_missing_paths_are_delivered_without_filesystem_access() {
        let cwd = std::env::temp_dir();
        let relative = format!("{}.md", "長い名前".repeat(100));
        let absolute = cwd.join(relative).into_os_string().into_string().unwrap();
        assert_eq!(args(&["app", &absolute], None), vec![absolute]);
    }

    #[test]
    fn cold_requests_survive_until_ready_and_legacy_pop_keeps_rest() {
        let pending = OpenFileState::default();
        pending.enqueue(["first.md".into(), "second.md".into()]);
        pending.enqueue(["second.md".into(), "third.md".into()]);
        assert_eq!(pending.pop().as_deref(), Some("first.md"));
        assert_eq!(pending.drain(), vec!["second.md", "third.md"]);
        assert!(pending.drain().is_empty());
        assert!(pending.pop().is_none());
    }

    #[test]
    fn warm_request_for_a_previously_drained_document_is_not_lost() {
        let pending = OpenFileState::default();
        pending.enqueue(["same.md".into()]);
        assert_eq!(pending.drain(), vec!["same.md"]);
        pending.enqueue(["same.md".into(), "next.md".into()]);
        assert_eq!(pending.drain(), vec!["same.md", "next.md"]);
    }

    #[test]
    fn concurrent_enqueue_is_not_lost_during_drain() {
        let pending = std::sync::Arc::new(OpenFileState::default());
        let writer = pending.clone();
        let thread =
            std::thread::spawn(move || writer.enqueue((0..100).map(|index| format!("{index}.md"))));
        let mut received = pending.drain();
        thread.join().unwrap();
        received.extend(pending.drain());
        assert_eq!(
            received,
            (0..100)
                .map(|index| format!("{index}.md"))
                .collect::<Vec<_>>()
        );
    }
}
